# -*- coding: utf-8 -*-
"""
Get fe descriptions from wordnet
"""
import os
import json
from tqdm import tqdm
import pandas as pd
from nltk.corpus import wordnet as wn

FE_NAMES_P = "./ilp_descriptions/fe_names.csv"
FE_CACHE_P = "./ilp_descriptions/fe_cache.json"

if not os.path.exists(FE_CACHE_P):
    FE_CACHE = {}
else:
    with open(FE_CACHE_P, 'r', encoding="utf-8") as f:
        FE_CACHE = json.load(f)

HARD_CODED_CACHE = {
    "Abundant_entities": "Entities that are present in large quantities or in abundance within an event or context.",
    "Added_set": "A collection of elements or entities that are introduced or included in a situation or process.",
    "Addictant": "An entity that causes or contributes to addiction or dependency within a scenario.",
    "Affected_party": "The entity directly impacted or influenced by an event or action.",
    "AggregateProperty": " A characteristic or attribute that results from the combination or summation of individual components or entities.",
    "Alignment_mismatch": "A situation where elements or components do not align or correspond correctly, creating inconsistencies or conflicts.",
    "Allowed_category": "A classification of elements or actions that are permitted within a given context or framework.",
    "Amount_of_discussion": "The extent or degree of verbal exchange in an event or process, often measured by quantity or intensity.",
    "Amount_of_information": "The total quantity of information conveyed or shared within a given context.",
    "Amount_of_work": "The total effort, tasks, or activities required or performed within an event or process.",
    "Base_position": "The starting or reference point from which further actions, decisions, or measurements are made.",
    "Basis_of_order": "The fundamental principles or criteria that determine the organization or arrangement of elements within a system.",
    "Binding_principle": "A fundamental rule or law that imposes obligation or enforces certain actions within a given context.",
    "Body_location": "The specific physical location or region of a body (human, animal, or other entity) within an event or situation.",
    "Business_Name": "The formal designation or title by which a business or organization is recognized or identified.",
    "Cause_of_shine": "The source or reason for something emitting light or appearing bright in a given context.",
    "Change_agent": "An entity or factor that brings about or facilitates a transformation or shift in a system, behavior, or state.",
    "Character_of_end_state": "The defining attributes or qualities of the final condition or result of an event or process.",
    "Co_Variable": "A variable that is related or associated with another, often in a joint or simultaneous manner within an event or process.",
    "Co_participant": "An entity that participates alongside others in an event, action, or situation.",
    "Co_resident": "An entity that shares the same location or environment as another, particularly in the context of living or residing together.",
    "Co_theme": "An entity that shares or participates in the same thematic role or subject matter within an event or situation.",
    "Cognate_event": "An event related to or occurring alongside another event, typically sharing a common origin or theme.",
    "Cognizer": "The entity perceiving or recognizing an event, action, or situation.",
    "Color_qualifier": "A descriptor that defines the characteristics or attributes of color within a given context.",
    "Communicative_act": "An action or utterance intended to convey information, intention, or emotion in communication.",
    "Comparand": "An entity or item used for comparison against another to evaluate similarities or differences.",
    "Comparison_set": "A group of entities or items considered together for the purpose of comparison.",
    "Compeller": "An entity or force that induces or forces another entity to act or behave in a particular way.",
    "Competing_consideration": "An alternative factor or concern that competes for attention or priority in decision-making.",
    "Component_entities": "The individual entities that make up or contribute to a larger system or whole.",
    "Connected_item": "An object or entity that is linked or associated with another item in a specific context",
    "Connected_locations": "Locations that are spatially or contextually linked or related in some way.",
    "Constituent_parts": "The basic components or elements that collectively form a larger whole.",
    "Container_portal": "An opening or access point through which an entity can enter or exit a container.",
    "Container_possessor": "The entity that owns or controls a container and its contents.",
    "Containing_event": "An event that encompasses or includes another event within its broader context.",
    "Containing_text": "A body of text that includes or surrounds another text or segment within it.",
    "Context_of_acquaintance": "The background or environment in which an entity becomes familiar with another entity.",
    "Contract_basis": "The foundational terms or conditions that form the basis of a formal agreement or contract.",
    "Contrast_set": "A group of items or entities used to highlight differences between them within a given context.",
    "Contrastive_context": "A situation or environment that emphasizes the differences between entities or events.",
    "Conveyed_emotion": "The emotional state or feeling communicated by an entity during an event or action.",
    "Coordinated_event": "Events that are planned or occur together in a synchronized manner.",
    "Correlated_event": "Events that are related or associated due to a shared influence or cause.",
    "Counter_actor": "An entity that opposes or acts in contrast to another entity within a given event or situation.",
    "Countertransfer": "The transfer of something in response to a previous transfer, often in a reciprocal or opposing manner.",
    "Crime_jurisdiction": "The legal authority or area within which a crime is considered to fall under a specific legal system.",
    "Current_jurisdiction": "The jurisdiction or legal authority currently overseeing an event, action, or issue.",
    "Dangerous_entity": "An entity that poses a potential threat or harm to others within a given context.",
    "Dangerous_situation": "A scenario or event that presents risks or threats to the entities involved.",
    "Decoration_descriptor": "A term or attribute that describes the decorative features or qualities of an object or space.",
    "Dedicated_entity": "An entity that is specifically assigned or devoted to a particular purpose or function.",
    "Dedicated_type": "A classification or category of entity that is exclusively designed or set aside for a specific role or purpose.",
    "Degree_of_involvement": "The level or extent to which an entity participates or is engaged in a particular event or action.",
    "Delivery_device": "An object or mechanism used to transfer or convey something to a destination.",
    "Dependent_entity": "An entity whose existence or action is reliant on another entity or condition.",
    "Dependent_individual": "An individual whose actions or state are influenced by or contingent upon another.",
    "Dependent_situation": "A situation that arises or persists only due to the existence or occurrence of another event or condition.",
    "Dependent_state": "A state that is determined or sustained by an external entity or condition.",
    "Described_entity": "An entity that is depicted, represented, or characterized in a particular way within a context.",
    "Desirable_situation": "A situation that is regarded as favorable or preferred within a given context.",
    "Desired_state": "A specific condition or outcome that is sought or intended in an event or action.",
    "Differentiating_fact": "A fact or element that distinguishes one entity or situation from another.",
    "Discourse_salient_country": "A country that is particularly emphasized or relevant in a discourse or conversation.",
    "Domain_of_relevance": "The specific context or area in which particular entities, events, or concepts are significant or applicable.",
    "Duration_of_endstate": "The length of time during which a final condition or state persists after an event or action.",
    "Duration_of_final_state": "The time period in which the ultimate condition or state of an event remains unchanged.",
    "Duration_of_state": "The amount of time for which a particular state or condition is sustained.",
    "Empathy_target": "The entity or individual to whom empathy is directed or applied in a given context.",
    "Enabled_action": "An action that is made possible or facilitated by a particular condition or entity.",
    "Enablement": "The process or condition that allows an entity to perform a specific action or behavior.",
    "Enclosed_region": "A spatial area or environment that is surrounded or contained by boundaries.",
    "End_time": "The point in time when an event or state concludes or ceases.",
    "Entity1": "The first entity in a relationship or interaction.",
    "Entity2": "The second entity in a relationship or interaction.",
    "Entry_path": "The route or means by which an entity enters a space or context.",
    "Epistemic_stance": "The position or attitude an individual takes regarding the certainty, belief, or knowledge about an event or proposition.",
    "Evaluee": "The entity being evaluated or assessed within a given context.",
    "Event_description": "A narrative or representation that outlines the details and components of an event.",
    "Existing_member": "An entity that is already part of a group, system, or category.",
    "Expected_entity": "An entity anticipated to participate in or occur within a specific context.",
    "Expected_event": "An event that is anticipated to happen based on prior information or conditions.",
    "Experiencer": "The entity that perceives, feels, or undergoes an experience in a particular event or situation.",
    "Exporting_area": "A region or zone from which goods, services, or information are sent or transferred to another.",
    "Expressor": "The entity that conveys or communicates an emotion, thought, or intention in a given context.",
    "External_cause": "A factor or force outside of an entity that triggers or influences an event or condition.",
    "Final_category": "The last classification or category that an entity or event is assigned to after a process or transformation.",
    "Final_correlate": "The final entity or condition that is associated or corresponds with another in a process or event.",
    "Final_state": "The ultimate condition or outcome after a series of events or actions.",
    "Final_value": "The concluding measurement, quantity, or quality of an entity after a process or event.",
    "Fixed_location": "A location that remains constant and does not change over time.",
    "Focal_entity": "The primary entity of focus within a specific context or event.",
    "Focal_participant": "The main participant in an event or scenario that is the primary focus of attention.",
    "Following_distance": "The spatial gap or distance maintained between entities as they move or interact.",
    "Formational_cause": "The cause or factor responsible for the formation or creation of something.",
    "Frequency_of_use": "The rate or regularity with which an entity or action is employed or utilized.",
    "Governing_authority": "The entity or institution that holds the power to regulate, enforce, or manage certain actions or entities.",
    "Gradable_attribute": "An attribute that can be measured along a scale or spectrum, indicating varying degrees or intensities.",
    "Hair_Property": "A characteristic or trait associated with the hair of an entity, such as texture, color, or length.",
    "Harmful_event": "An event that causes damage, injury, or negative impact to an entity or environment.",
    "Holding_location": "The location where an entity or item is stored, kept, or held temporarily.",
    "Honored_entity": "An entity that is recognized, respected, or celebrated for its actions or contributions in a specific context.",
    "Host_location": "The location or environment that hosts or accommodates another entity or group.",
    "Hot_Cold_source": "An entity or factor that produces or is associated with extreme temperatures (either hot or cold).",
    "Illicit_organization": "A group or entity engaged in illegal or unlawful activities within a particular context.",
    "Impactors": "Entities or factors that have a significant influence or effect on a situation or condition.",
    "Importing_area": "A region or zone that receives goods, services, or information from an external source.",
    "Influencing_entity": "An entity that exerts influence or control over another entity or event within a given context.",
    "Influencing_situation": "A situation in which an entity or factor has a significant impact on the course or outcome of events.",
    "Influencing_variable": "A variable that alters or affects the outcome or behavior of a situation or system.",
    "Inherent_purpose": "The fundamental or intrinsic goal or reason behind the existence or function of an entity or action.",
    "Initial_State": "The starting condition or state of an entity or event before it undergoes any changes.",
    "Initial_category": "The first classification or category assigned to an entity or event at the outset.",
    "Initial_correlate": "The initial entity or condition that corresponds with another at the beginning of an event or process.",
    "Initial_set": "The original collection of entities or elements present at the beginning of an event or scenario.",
    "Initial_size": "The size or magnitude of an entity or event at the beginning of a process.",
    "Initial_state": "The condition of an entity or event before it undergoes any changes or transformations.",
    "Initial_subevent": "The first subevent or phase within a larger event or process.",
    "Initial_value": "The starting value or measurement of an attribute or condition at the beginning of a process.",
    "Instance_Prop": "A specific property or characteristic associated with an instance of an entity or event.",
    "Intended_event": "An event that is planned or expected to happen as a result of certain actions or decisions.",
    "Intended_goal": "The specific objective or outcome that is sought or desired by an agent in an event or action.",
    "Intended_perceiver": "The individual or entity for whom a perception or experience is intended or directed.",
    "Intended_purpose": "The specific aim or function that an action or entity is meant to fulfill.",
    "Intended_referent": "The entity or object that a statement, gesture, or communication is intended to refer to or represent.",
    "Interested_party": "An entity or individual that has a vested interest or concern in a particular event, action, or decision.",
    "Internal_cause": "A cause or factor originating within an entity that influences its behavior or condition.",
    "Invasion_act": "An action or event that involves the intrusion or unlawful entry into a space or territory.",
    "Item_2": "The second item in a set or pair of related items.",
    "Item_Property": "A characteristic or attribute associated with a specific item or object.",
    "Landmark_entity": "An entity that serves as a point of reference or notable feature in a given context or location.",
    "Last_subevent": "The final subevent or phase in a larger event or process.",
    "Legal_basis": "The foundational legal principles or framework that support or justify an action, decision, or agreement.",
    "Limit1": "The first boundary or constraint within a defined range or context.",
    "Limit2": "The second boundary or constraint within a defined range or context.",
    "Location_of_Event": "The specific place or area where an event occurs or takes place.",
    "Location_of_appearance": "The location where an entity or event is first noticed or revealed.",
    "Location_of_communicator": "The place or setting from which a communicator conveys a message or information.",
    "Location_of_confinement": "The physical space or area where an entity is confined or restricted.",
    "Location_of_inspector": "The location from which an inspector observes, examines, or evaluates an entity or process.",
    "Location_of_participant": "The place or setting in which a participant is situated during an event or action.",
    "Location_of_perceiver": "The location from which a perceiver observes or experiences an event or phenomenon.",
    "Location_of_protagonist": "The location where the central character or participant in an event is situated or involved.",
    "Location_of_representation": "The place or medium in which a representation of an entity or event is presented or displayed.",
    "Location_of_source": "The location from which something originates or is sourced.",
    "Location_of_tester": "The location where a test or evaluation is conducted or performed.",
    "Main_statement": "The primary or central assertion made within a discourse or communication.",
    "Market_type": "The classification or category of a market based on its characteristics or focus (e.g., consumer, wholesale).",
    "Means_of_Gathering": "The method or tool used to collect data, information, or resources.",
    "Means_of_propulsion": "The method or mechanism used to move or propel an entity, especially in transportation contexts.",
    "Member_1": "The first entity in a membership or group.",
    "Member_2": "The second entity in a membership or group.",
    "Mode_of_transfer": "The method or process by which something is transferred or conveyed from one entity to another.",
    "Mode_of_transportation": "The method or means by which an entity or goods are transported from one location to another.",
    "Name_source": "The origin or entity from which a name is derived or attributed.",
    "New_Status": "A newly assigned condition, role, or situation an entity occupies after a change or event.",
    "New_punishment": "The punishment or penalty that is newly assigned to an entity after a transgression.",
    "New_tool": "A tool or instrument that is introduced or newly acquired for use.",
    "Next_subevent": "The subsequent event or phase in a sequence of actions or occurrences.",
    "Normal_location": "The typical or expected place where an entity or event occurs.",
    "Number_of_possibilities": "The total count of potential outcomes or choices available in a scenario.",
    "Obscuring_medium": "A substance or entity that blocks or hinders visibility or perception.",
    "Old_leader": "A previous individual or entity that held a leadership position.",
    "Old_order": "A previous system or arrangement of entities or events before a change occurred.",
    "Old_tool": "A tool or instrument that was previously used before being replaced or upgraded.",
    "Option_1": "The first choice or alternative available in a decision-making process.",
    "Option_2": "The second choice or alternative available in a decision-making process.",
    "Ordinality": "The characteristic of being arranged in a specific order or sequence.",
    "Original_owner": "The initial individual or entity that possessed or controlled something.",
    "Original_punishment": "The first punishment or penalty assigned for a transgression or wrongdoing.",
    "Part_1": "The first segment or component of a larger whole or event.",
    "Part_2": "The second segment or component of a larger whole or event.",
    "Part_of_form": "A component or element that contributes to the structure or shape of a larger entity.",
    "Participant_1": "The first individual or entity involved in an event or action.",
    "Participant_2": "The second individual or entity involved in an event or action.",
    "Particular_iteration": "A specific occurrence or repetition of an event or process.",
    "Party_1": "The first group or entity involved in a relationship, contract, or event.",
    "Party_2": "The second group or entity involved in a relationship, contract, or event.",
    "Path_shape": "The specific form or outline of a route or trajectory taken by an entity.",
    "Performer1": "The first entity responsible for carrying out or initiating an action or event.",
    "Performer2": "The second entity responsible for carrying out or initiating an action or event.",
    "Period_of_existence": "The length of time during which an entity or state remains in existence.",
    "Period_of_iteration": "The span of time during which a process or event is repeated or iterated.",
    "Period_of_iterations": "The total time span encompassing multiple iterations or repetitions of an event or process.",
    "Persistent_characteristic": "A feature or trait that remains consistent or enduring over time.",
    "Phenomenon_1": "The first observable event or occurrence in a particular context.",
    "Phenomenon_2": "The second observable event or occurrence in a particular context.",
    "Piece_prop": "A characteristic or property associated with a specific piece or segment of a larger whole.",
    "Place_holder": "An entity or symbol used to temporarily represent another entity or concept.",
    "Place_of_employment": "The location where an individual or entity performs work or job-related activities.",
    "Point_of_contact": "The designated entity or location for communication or interaction in a process or event.",
    "Position_qualifier": "A descriptor that specifies the role or rank of an entity within a given position.",
    "Possible_event": "An event that could occur based on certain conditions or possibilities.",
    "Post_state": "The condition or situation of an entity after a change or event has occurred.",
    "Potential_observer": "An entity that has the capacity or possibility to observe an event or situation.",
    "Power_source": "The origin or mechanism that provides energy or power for an entity or system.",
    "Preparatory_phase": "The initial stage in a process where actions are taken to set up or prepare for a later event.",
    "Preventing_cause": "An entity or factor that stops or hinders an event or action from occurring.",
    "Previous_context": "The conditions or circumstances that existed before the current situation or event.",
    "Previous_instance": "The prior occurrence of an event or situation in a sequence.",
    "Prior_state": "The condition or situation of an entity before a particular change or event took place.",
    "Profiled_attribute": "A specific characteristic or feature of an entity that is highlighted or examined in detail.",
    "Profiled_region": "A specific area or region that is focused on or analyzed in a given context.",
    "Protagonist_1": "The first main character or central participant in an event or narrative.",
    "Protagonist_2": "The second main character or central participant in an event or narrative.",
    "Purpose_of_Event": "The intended goal or objective that an event seeks to accomplish.",
    "Purpose_of_created_entity": "The intended function or use for which an entity was created or designed.",
    "Purpose_of_goods": "The intended use or function of a particular item or product.",
    "Purpose_of_theme": "The central idea or objective that a particular theme aims to convey or achieve.",
    "Q_Prop": "A specific property or characteristic related to a particular question or inquiry.",
    "Re-encoding": "The process of transforming or altering information into a different format or representation.",
    "Reference_occasion": "The specific instance or occasion used as a reference point in a given context.",
    "Reference_quantity": "The amount or quantity used as a standard or reference in a comparison or evaluation.",
    "Regulated_entity": "An entity subject to rules, laws, or guidelines governing its behavior or actions.",
    "Related_event": "An event that is connected or associated with another event in some way.",
    "Relation_type": "The specific nature or category of connection between two entities or events.",
    "Relative_location": "The position of an entity in relation to another entity or reference point.",
    "Relative_time": "The measurement of time based on a reference event or state.",
    "Relevant_feature": "A characteristic or aspect that is significant or important within a given context.",
    "Required_entity": "An entity that is necessary or essential for a specific event or process to occur.",
    "Required_individual": "An individual who is needed or mandatory for a task or event.",
    "Resistant_surface": "A surface that is capable of resisting external forces, damage, or wear.",
    "Responding_entity": "An entity that reacts or responds to an action, stimulus, or event.",
    "Responsible_party": "The entity or individual accountable for an action, event, or decision.",
    "Result_size": "The magnitude or scale of the outcome or result of an event or process.",
    "Resultant_Situation": "The situation or condition that arises as a consequence of an event or action.",
    "Resultant_action": "The action or behavior that occurs as a result of a preceding event or action.",
    "Resulting_action": "An action that directly follows from a previous event or process.",
    "Role_of_focal_participant": "The specific function or responsibility held by the primary participant in an event.",
    "Salient_activity": "An activity that is prominent or significant within a given context or event.",
    "Salient_entity": "An entity that stands out or is most noticeable within a specific situation.",
    "Seat_of_emotion": "The location or source of an emotion within an individual or entity.",
    "Sensory_attribute": "A characteristic related to the perception of an entity through the senses (e.g., sight, touch).",
    "Sentient_entity": "An entity capable of experiencing sensations or emotions.",
    "Set_of_instances": "A collection of specific occurrences or examples of an entity or event.",
    "Shape_prop": "A characteristic related to the form or configuration of an entity.",
    "Side_1": "The first side or aspect of an object or entity.",
    "Side_2": "The second side or aspect of an object or entity.",
    "Sign_1": "The first indicator or symbol representing an idea, condition, or event.",
    "Sign_2": "The second indicator or symbol representing an idea, condition, or event.",
    "Simulated_entity": "An entity that is artificially created or modeled to represent a real entity or phenomenon.",
    "Size_change": "A modification in the dimensions or magnitude of an entity.",
    "Sleep_state": "The condition or state of an entity when it is in a period of rest or unconsciousness.",
    "Sought_entity": "An entity that is being searched for or desired in a given context.",
    "Source_emitter": "The origin or entity responsible for emitting or producing a signal or energy.",
    "Source_material": "The raw material or substance from which something is created or derived.",
    "Source_of_authority": "The origin or entity that holds the power to make decisions or enforce rules.",
    "Source_of_information": "The origin or entity from which information is obtained or communicated.",
    "Source_of_legal_authority": "The entity or system that grants the power to make legal decisions or enforce laws.",
    "Source_of_relationship": "The origin or entity that initiates or establishes a relationship between entities.",
    "Source_representation": "The original or primary representation of an entity or event from which others are derived.",
    "Specified_content": "The particular information, material, or details that are explicitly mentioned or described.",
    "Specified_entity": "An entity that is clearly identified or defined within a context.",
    "Standard_attribute": "A characteristic that is generally accepted as a norm or benchmark for comparison.",
    "Standard_item": "An item that is considered typical or representative within a given category.",
    "Start_time": "The moment or point in time when an event or process begins.",
    "State_of_represented": "The condition or situation of an entity that is being represented or depicted.",
    "Sub_event": "A smaller or secondary event that is part of a larger event or process.",
    "Sub_source": "A secondary or subordinate source from which information or material originates.",
    "Sub_part": "A smaller component or piece that is part of a larger whole.",
    "Sub_region": "A smaller region or area within a larger geographical or conceptual region.",
    "Subregion_bodypart": "A specific smaller part or section of a body region.",
    "Subtype": "A more specific category or type within a broader classification.",
    "Target_group": "The specific group or audience that an action, message, or event is aimed at.",
    "Target_location": "The specific place or area intended for the focus or destination of an action or event.",
    "Target_representation": "The specific form or depiction of an entity or event aimed at conveying a message or idea.",
    "Temperature_goal": "The desired temperature level to be achieved or maintained.",
    "Temperature_setting": "The specific temperature selected or configured for a particular purpose.",
    "Temperature_start": "The initial temperature at the beginning of a process or event.",
    "Term1": "The first of two terms or elements in a relationship or comparison.",
    "Term2": "The second of two terms or elements in a relationship or comparison.",
    "Term_of_sentence": "The specific period or duration of punishment imposed as part of a legal sentence.",
    "Tested_property": "A characteristic or attribute of an entity that has been examined or evaluated.",
    "Theme_1": "The first central idea or subject that is explored or represented in a context.",
    "Theme_2": "The second central idea or subject that is explored or represented in a context.",
    "Time_of_Event": "The specific moment or period when an event takes place.",
    "Time_of_Eventuality": "The time when a potential or hypothetical event might occur.",
    "Time_of_creation": "The moment or period when something is created or brought into existence.",
    "Time_span": "The total duration or length of time during which an event or condition occurs.",
    "Topical_entity": "An entity that is the subject or focus of a particular discussion or context.",
    "Toxin_source": "The origin or entity responsible for producing or emitting a toxin.",
    "Trajector": "The entity or object that is the primary focus of movement in a spatial event.",
    "Trajector_event": "An event in which the primary entity undergoes movement or change in position.",
    "Transitional_period": "The phase of change or transformation between two different states or conditions.",
    "Travel_means": "The method or mode by which an entity moves from one location to another.",
    "Type_Property": "A characteristic that defines or classifies an entity within a specific type or category.",
    "Uncertain_situation": "A scenario where the outcomes or conditions are unclear or ambiguous.",
    "Undergoer": "An entity that experiences or undergoes an action or event.",
    "Unwanted_characteristics": "Negative or undesirable traits or properties associated with an entity.",
    "Useful_location": "A place or area that serves a functional or practical purpose.",
    "Value_range": "The span or limits of acceptable or measurable values for a particular attribute.",
    "Wielder": "The entity or individual who holds or controls an object or tool.",
    "World_state": "The overall condition or situation of the world or environment at a given time.",
    "Sub-region": "A smaller or specific part of a larger region.",
    "Concept1": "The first idea or abstract notion in a comparison or relationship.",
    "Concept2": "The second idea or abstract notion in a comparison or relationship.",
    "Extent_of_acclaim": "The degree or level of recognition, praise, or approval an entity receives.",
  "Means_of_communication": "The method or medium used to convey information or messages.",
  "Negative_consequences": "The harmful or undesirable outcomes resulting from an event or action."
}


def main():
    data = pd.read_csv(FE_NAMES_P)
    fes = data.fe.unique()
    for fe in tqdm(fes):
        if fe not in FE_CACHE:
            if fe.split('/')[-1] in HARD_CODED_CACHE:
                des = HARD_CODED_CACHE[fe.split('/')[-1]]
            else:
                des = wn.synsets(fe.split('/')[-1].lower())[0].definition()
            FE_CACHE[fe] = des

if __name__ == '__main__':
    main()